### PR TITLE
Team formation

### PR DESCRIPTION
**Pull request by KenG98**
Team formation forms work on both the front and back end. Nav to localhost:8080/team-formation to check it out. This give us access to it but we shouldn't advertise it to participants till we test this form as a team.

### CODE REVIEW

**Comment by anna1go** [comment]
I added a link to this form in the profile page in a [separate PR ](https://github.com/Bostonhacks/headstart/pull/60).

**Review by anna1go — APPROVED** [review]
I want to get this live tested by people.

**Review by lkwatson — CHANGES_REQUESTED** [review]
Found a bug. 

`registration-gather-data.js`, line 50: "Uncaught TypeError: Cannot read property 'labels' of undefined"

Reproduce: New application, navigate to `/team-formation`, select any checkbox, for example under the first question "What areas are you most interested in?"

**Comment by anna1go** [comment]
@lkwatson I've clicked around on it, and I found that this error gets thrown if you click directly on the text of the checkbox and not on the checkbox itself. Even though that happens, the app still sends the data. 

What's interesting though, is that the server hangs after 6 or so ajax requests. I have to manually restart the server for it to receive data from the frontend again.

**Comment by anna1go** [comment]
Has anyone else encounter the server hanging issue?

**Comment by KenG98** [comment]
I noticed that too but it works regardless. That's @agoncharova's forte though, so I'll let her take a look.

**Comment by anna1go** [comment]
Ya, I mean it doesn't make a difference, data gets sent

**Comment by KenG98** [comment]
I'm not able to reproduce the server hanging issue. What version of Node are you using? Is anything logged to the console when it hangs?

**Comment by anna1go** [comment]
I have node version 7.0.0. I mean it quite literally stops accepting reqs and the page reload takes  a while. Nothing logged to the console, but the last request

**Comment by KenG98** [comment]
@agoncharova I have had this issue with node 7 on a different project, I have no explanation! Could you see if it's the case with node 6, the LTS? Thanks!

**Comment by KenG98** [comment]
I can't figure out authenticating the supertest agent so that it can test the team formation pages... I'm going to merge this anyways as I have manually tested it, and we need to let the bostonhacks team try it asap so that we can get that sample data and get it to participants. I'll fix the tests soon.

**Comment by anna1go** [comment]
🎉🎉🎉

**Pull request merged**
